resolver: lts-6.23

packages:
- '.'
- 'vendor/tabl'
- 'vendor/trifecta'

extra-deps:
- llvm-general-3.5.1.2
- llvm-general-pure-3.5.1.0

flags:
  llvm-general:
    shared-llvm: true

extra-package-dbs: []

extra-lib-dirs:
- /usr/local/Cellar/libffi/3.0.13/lib/
