resolver: lts-6.23

packages:
- '.'
- 'vendor/tabl'
- 'vendor/trifecta'

extra-deps:
- llvm-general-3.5.1.2
- llvm-general-pure-3.5.1.0
- freer-effects-0.3.0.1
- text-metrics-0.2.0

flags:
  llvm-general:
    shared-llvm: true

extra-package-dbs: []

extra-lib-dirs:
- /usr/local/Cellar/libffi/3.0.13/lib/
- /usr/local/Cellar/v8/5.1.281.47/lib

local-bin-path: ./bin
